
export const mock_cart = [
	{
		image: '/assets/images',
		name: 'XX99 MK II',
		model: 'xx99-mk-ii',
		category: 'speakers' as const,
		description: '---',
		price: 2999,
		qty: 5,
		cart_qty: 2,
	},
	{
		image: '/assets/images',
		name: 'XX99 MK IV',
		model: 'xx99-mk-iv',
		category: 'speakers' as const,
		description: '---',
		price: 399,
		qty: 1,
		cart_qty: 1,
	},
	{
		image: '/assets/images',
		name: 'XX99 MK III',
		model: 'xx99-mk-iii',
		category: 'speakers' as const,
		description: '---',
		price: 599,
		qty: 3,
		cart_qty: 3,
	},
	{
		image: '/assets/images',
		name: 'XX99 MK I',
		model: 'xx99-mk-i',
		category: 'speakers' as const,
		description: '---',
		price: 799,
		qty: 1,
		cart_qty: 1,
	},
]
